arrowParens: avoid
bracketSpacing: true
endOfLine: auto
printWidth: 120
singleQuote: false
tabWidth: 2
trailingComma: all

overrides:
  - files: ["*.sol"]
    options:
      tabWidth: 2
      printWidth: 120
      bracketSpacing: true
      trailingComma: none
